Added measures to avoid performance hungy asssert handling
stevencohn/OneMore pull request #1687
Opened 2024-11-28 20:40 UTC by weissm

## IS YOUR COMMIT SIGNED?
Note that this repo requires all commits to be properly signed, [see here](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more info

## Enhancement or Defect Addressed by This PR
Enhancement 

## Description of Proposed Changes
Added additional condition to check saved stated to avoid later assert which is very performance hungry

2024-11-29 14:03 UTC, stevencohn requested changes
Where are the asserts to which you refer? Internals to the SQLite library?

2024-11-29 14:03 UTC, stevencohn commented on OneMore/Commands/Tagging/HashtagService.cs
> +			} else
This ignores and breaks the "all" notebooks condition. While the UI currently might avoid this case, it was an intentional and possible future case. I want to leave it in.

2024-11-29 14:03 UTC, stevencohn commented on OneMore/Commands/Tagging/HashtagScanner.cs
> +			var saved = (candidates.Count() == 0) ? null : provider.ReadPageTags(pageID);
This break the case where there are no longer hashtags on the page but there used to be, and now the scanner will not delete the old hashtags in the db.

2024-12-22 14:16 UTC, stevencohn requested changes

2024-12-22 14:16 UTC, stevencohn commented on OneMore/Commands/Tagging/HashtagScanner.cs
> +			// in case of empty candidate list do not read page tags as it throws exception
I haven't been able to reproduce this case. How would it happen?

2024-12-22 14:16 UTC, stevencohn commented on OneMore/Commands/Tagging/HashtagService.cs
> +			} else
ping

2024-12-23 09:01 UTC, weissm commented
I also deep dive into this problem. What appearntly happend on my side was that the sql file "OneMore.db" was corrupted. With this the assert was multiple times called, caused to slow down my onenote system. After removing the file it was newly created and apperently did not show this behavior again. Not clear if there is a chance to double check the consistancy of OneMore.db. Otherwise, this issue could be closed.

2024-12-23 13:59 UTC, closed without merging